version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true'
  secrets-manager:
    GIVE_CI_USERNAME: give-ci-sandbox-secrets:GIVE_CI_USERNAME
    GIVE_CI_PASSWORD: give-ci-sandbox-secrets:GIVE_CI_PASSWORD
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      # Install CF CLI
      - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
      - dpkg -i cf-cli_amd64.deb
      - cf -v
  pre_build:
    commands:
      # Clean any stale artifacts
      - mvn $MAVEN_CLI_OPTS clean
  build:
    commands:
      - echo Build started on `date`
      # Automatically compiles and runs test
      - mvn $MAVEN_CLI_OPTS package
  post_build:
    commands:
      - echo Build completed on `date`
      # Login to cloud.gov
      - cf login -a https://api.fr.cloud.gov -u $GIVE_CI_USERNAME -p $GIVE_CI_PASSWORD
      # Push app to cloud.gov and create a random route to avoid collision, but don't start it yet
      - cf push -m 512M --no-start --random-route
      # Set memory allocation for the JVM to 128M
      - cf set-env give-ipp-usps JAVA_OPTS '-XX:ReservedCodeCacheSize=128M'
      # Start the application
      - cf start give-ipp-usps
reports:
  # Push test reports to AWS Code
  test-report:
    files:
      - '**/*'
    base-directory: target/surefire-reports
    discard-paths: true
cache:
  paths:
   - '/root/.m2/**/*'
   - '/root/.npm/**/*'
   - 'build/**/*'